fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
    epel:
      repo: git://github.com/stahnma/puppet-module-epel.git
    sudo:
      repo: https://github.com/saz/puppet-sudo.git
    yum:
      repo: https://github.com/CERIT-SC/puppet-yum.git
  symlinks:
    x2go: "#{source_dir}"
